jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: ${JENKINS_ADMIN_ID}
         password: ${JENKINS_ADMIN_PASSWORD}
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"
  remotingSecurity:
    enabled: true
security:
  queueItemAuthenticator:
    authenticators:
    - global:
        strategy: triggeringUsersAuthorizationStrategy
unclassified:
  location:
    url: http://127.0.0.1:${JENKINS_PORT}/
  sonarGlobalConfiguration:
    buildWrapperEnabled: false
    installations:
    - name: "wilkebouwer-itvb23ows-starter-code-sonarqube"
      serverUrl: http://sonarqubeserver:${SONARQUBE_PORT}
      triggers:
        skipScmCause: false
        skipUpstreamCause: false
tool:
  sonarRunnerInstallation:
    installations:
    - name: "SonarScanner"
      properties:
      - installSource:
          installers:
          - sonarRunnerInstaller:
              id: "5.0.1.3006"
          - sonarRunnerInstaller:
              id: "5.0.1.3006"
jobs:
  - script: >
      multibranchPipelineJob('wilkebouwer-itvb23ows-starter-code') {
          branchSources {
              git {
                  id = 'wilkebouwer-itvb23ows-starter-code'
                  remote('https://github.com/wilkebouwer/itvb23ows-starter-code')
              }
          }
      }
